# AWS CodeBuild pipeline
version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "https://s3.console.aws.amazon.com/s3/buckets?region=us-west-1&region=us-west-1"
    BUILD_FOLDER: "dist"
    BUILD_ENV: "prod"
    BUILD_DIR: "/frontend/one-nation-auto-loan-ff"
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - cd ${BUILD_DIR}
      - ng build --configuration production --aot
  post_build:
     commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
