# AWS CodeBuild pipeline
version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "angular-leads-app"
    BUILD_FOLDER: "dist/one-nation-auto-loan-ff"
    BUILD_ENV: "prod"
    BUILD_DIR: "./frontend/one-nation-auto-loan-ff"
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - cd ${BUILD_DIR}
      - npm install --legacy-peer-deps
      - ng build --configuration production --aot
  post_build:
     commands:
      - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  secondary-artifacts:
    angulardevopsartifact:
      files:
         - '**/*.html'
         - '**/*.js'
         - '**/*.css'
         - '**/*.ico'
      base-directory: 'frontend/one-nation-auto-loan-ff/dist'
      discard-paths: yes
